type Task {
    id: ID!
    name: String!
    description: String
    completed: Boolean
    archive: Boolean
    created_at: DateTime
    deleted_at: DateTime
    client: Client
}

type TaskResponseMutation implements ResponseMutation {
    code: String
    ok: Boolean!
    message: String!
    task: Task
}

input TaskInput {
    name: String!
    description: String
    completed: Boolean
    archive: Boolean
}

extend type Query {
    task(id: ID!): Task
    tasks: [Task]
}

extend type Mutation {
    addTask(input: TaskInput!): TaskResponseMutation!
    updateTask(id: ID!, input: TaskInput!): TaskResponseMutation!
    deleteTask(id: ID!): TaskResponseMutation!
}